# Utiliser l'image officielle Apache comme image de base
FROM httpd:latest

# Copier le fichier index.html dans le dossier qui sert les pages web
COPY ./html/index.html /usr/local/apache2/htdocs/index.html

# Exposer le port 80 (facultatif, pour documentation)
EXPOSE 80
